title: "The Book Of Shen"
summary: "The Book of Shenをざっくり和訳しました。"
topics: ["lisp"] # トピック（5つまで）
published: true # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - example1 # チャプター1
  - example2 # チャプター2
  - example3 # チャプター3